version: '3'

services:
  backend:
    build: ./
    container_name: sonata_textile_container
    working_dir: /sonata_textile_shop
    ports:
      - 8010:8000
    volumes:
      - ./src:/sonata_textile_shop/src
      - ./commands:/sonata_textile_shop/commands
    command:
      - ./commands/start_server_dev.sh
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:16.1
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pg_data: { }