version: '3'

services:
  backend:
    build: ./
    container_name: sonata_textile_container
    working_dir: /sonata_textile_shop
    ports:
      - 8010:8000
    volumes:
      - ./src:/sonata_textile_shop/src
      - ./commands:/sonata_textile_shop/commands
    command:
      - ./commands/start_server_dev.sh
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:16.1
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: on-failure
    ports:
      - 5000:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    env_file:
      - .env
    depends_on:
      - postgres

  mongodb:
    image: mongo:3-stretch
    container_name: mongo_container
    restart: on-failure
    ports:
      - 27017:27017
    env_file:
      - .env
    volumes:
      - ./mongo_data:/data/db


volumes:
  pg_data: { }
  pgadmin_data: { }
  mongo_data: { }