version: '3'

services:
  backend:
    build: ./
    container_name: container_sonata_textile
    working_dir: /sonata_textile
    ports:
      - 8010:8000
    volumes:
      - ./src:/sonata_textile/src
      - ./commands:/sonata_textile/commands
      - static_content:/sonata_textile/src/static
      - media_content:/sonata_textile/src/media
    command:
      - ./commands/start_server_${MODE}.sh
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:16.1
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    container_name: container_pgadmin
    restart: on-failure
    ports:
      - 5000:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    env_file:
      - .env
    depends_on:
      - postgres

#  mongodb:
#    image: mongo:3-stretch
#    container_name: mongo_container
#    restart: on-failure
#    ports:
#      - 27017:27017
#    env_file:
#      - .env
#    volumes:
#      - ./mongo_data:/data/db

  nginx:
    image: nginx:1.19
    volumes:
      - static_content:/sonata_textile/src/static
      - media_content:/sonata_textile/src/media
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    depends_on:
      - backend

  redis:
    image: redis
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - backend

  celery:
    build: ./
    container_name: container_celery
    command:
      - ./commands/start_celery.sh
    restart: on-failure
    volumes:
      - ./src:/sonata_textile
      - ./commands:/sonata_textile/commands
      - media_content:/sonata_textile/media
      - static_content:/sonata_textile/static
    env_file:
      - .env
    depends_on:
      - redis
      - backend

  redisadmin:
    image: redislabs/redisinsight
    container_name: admin_redis
    restart: on-failure
    ports:
      - 8001:8001
    env_file:
      - .env

  flower:
    build: ./
    container_name: container_flower
    volumes:
      - ./src:/sonata_textile
    env_file:
      - .env
    command: celery -A config flower --broker=redis://redis
    ports:
      - 5555:5555
    depends_on:
      - celery

volumes:
  static_content: { }
  media_content: { }
  pg_data: { }
  pgadmin_data: { }
#  mongo_data: { }