# Generated by Django 4.2.7 on 2023-12-08 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=250)),
                (
                    "category",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Рушники"),
                            (1, "Ковдри"),
                            (2, "Постільна білизна"),
                            (3, "Подушки"),
                            (4, "Пледи"),
                            (5, "Покривала"),
                            (6, "Наматрацники"),
                            (7, "Скатертини"),
                            (8, "Декоративні наволочки"),
                            (9, "Кухонний текстиль"),
                        ]
                    ),
                ),
                ("price", models.IntegerField()),
                ("producing_country", models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="Towel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=150)),
                ("material", models.CharField(max_length=150)),
                ("size", models.CharField(max_length=50)),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Для рук"),
                            (1, "Для обличчя"),
                            (2, "Банні"),
                            (3, "Сауна"),
                            (4, "Набори"),
                            (5, "Куточки"),
                        ]
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="towels",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Blanket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(max_length=50)),
                ("cover_material", models.CharField(max_length=150)),
                ("filler", models.CharField(max_length=150)),
                (
                    "seasonality",
                    models.PositiveSmallIntegerField(choices=[(0, "Демісезонні"), (1, "Зимові"), (2, "Літні")]),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blankets",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BedLinen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=150)),
                (
                    "size",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Дитячий"),
                            (1, "Підлітковий"),
                            (2, "Полуторний"),
                            (3, "Двоспальний"),
                            (4, "Євро"),
                            (5, "Сімейний"),
                        ]
                    ),
                ),
                ("material", models.CharField(max_length=150)),
                ("size_duvet_cover", models.PositiveSmallIntegerField()),
                ("sheet_size", models.PositiveSmallIntegerField()),
                ("pillowcase_size", models.PositiveSmallIntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bed_linens",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
