# Generated by Django 4.2.7 on 2023-12-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_brand_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/img/products",
                verbose_name="Зображення",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="hit_sale",
            field=models.BooleanField(default=False, verbose_name="Хіт продаж"),
        ),
    ]
