# Generated by Django 4.2.7 on 2023-12-09 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_bedlinen_product_alter_blanket_product_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plaid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=150)),
                ("size", models.CharField(max_length=50)),
                ("material", models.CharField(max_length=150)),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Дитячий"),
                            (1, "Полуторний"),
                            (2, "Двоспальний"),
                            (3, "Євро"),
                        ]
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plaids",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pillow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=150)),
                ("size", models.CharField(max_length=50)),
                ("cover_material", models.CharField(max_length=150)),
                ("filler", models.CharField(max_length=150)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pillows",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bedspread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(max_length=50)),
                ("material", models.CharField(max_length=150)),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Дитячий"),
                            (1, "Полуторний"),
                            (2, "Двоспальний"),
                            (3, "Євро"),
                        ]
                    ),
                ),
                ("complete_set", models.CharField(max_length=150)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bedspreads",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
