# Generated by Django 4.2.7 on 2023-12-11 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_product_avatar_product_hit_sale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="img/products",
                verbose_name="Зображення",
            ),
        ),
    ]
