# Generated by Django 4.2.7 on 2023-12-09 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_plaid_pillow_bedspread"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bedlinen",
            options={
                "verbose_name": "Постільна білизна",
                "verbose_name_plural": "Постільна білизна",
            },
        ),
        migrations.AlterModelOptions(
            name="bedspread",
            options={"verbose_name": "Покривало", "verbose_name_plural": "Покривала"},
        ),
        migrations.AlterModelOptions(
            name="blanket",
            options={"verbose_name": "Ковдра", "verbose_name_plural": "Ковдри"},
        ),
        migrations.AlterModelOptions(
            name="pillow",
            options={"verbose_name": "Подушка", "verbose_name_plural": "Подушки"},
        ),
        migrations.AlterModelOptions(
            name="plaid",
            options={"verbose_name": "Плед", "verbose_name_plural": "Пледи"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Товар", "verbose_name_plural": "Товари"},
        ),
        migrations.AlterModelOptions(
            name="towel",
            options={"verbose_name": "Рушник", "verbose_name_plural": "Рушники"},
        ),
        migrations.AddField(
            model_name="product",
            name="availability",
            field=models.BooleanField(default=True, verbose_name="Наявність"),
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Опис"),
        ),
        migrations.AlterField(
            model_name="bedlinen",
            name="brand",
            field=models.CharField(max_length=150, verbose_name="Бренд"),
        ),
        migrations.AlterField(
            model_name="bedlinen",
            name="material",
            field=models.CharField(max_length=150, verbose_name="Матеріал"),
        ),
        migrations.AlterField(
            model_name="bedlinen",
            name="pillowcase_size",
            field=models.PositiveSmallIntegerField(verbose_name="Розмір наволочки"),
        ),
        migrations.AlterField(
            model_name="bedlinen",
            name="sheet_size",
            field=models.PositiveSmallIntegerField(verbose_name="Розмір простирадла"),
        ),
        migrations.AlterField(
            model_name="bedlinen",
            name="size",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Дитячий"),
                    (1, "Підлітковий"),
                    (2, "Полуторний"),
                    (3, "Двоспальний"),
                    (4, "Євро"),
                    (5, "Сімейний"),
                ],
                verbose_name="Спальний розмір",
            ),
        ),
        migrations.AlterField(
            model_name="bedlinen",
            name="size_duvet_cover",
            field=models.PositiveSmallIntegerField(verbose_name="Розмір підковдри"),
        ),
        migrations.AlterField(
            model_name="bedspread",
            name="complete_set",
            field=models.CharField(max_length=260, verbose_name="Комплектація"),
        ),
        migrations.AlterField(
            model_name="bedspread",
            name="material",
            field=models.CharField(max_length=150, verbose_name="Матеріал"),
        ),
        migrations.AlterField(
            model_name="bedspread",
            name="size",
            field=models.CharField(max_length=50, verbose_name="Розмір"),
        ),
        migrations.AlterField(
            model_name="bedspread",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Полуторний"), (1, "Євро")], verbose_name="Спальний розмір"
            ),
        ),
        migrations.AlterField(
            model_name="blanket",
            name="cover_material",
            field=models.CharField(max_length=150, verbose_name="Матеріал чохла"),
        ),
        migrations.AlterField(
            model_name="blanket",
            name="filler",
            field=models.CharField(max_length=150, verbose_name="Наповнювач"),
        ),
        migrations.AlterField(
            model_name="blanket",
            name="seasonality",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Демісезонні"), (1, "Зимові"), (2, "Літні")],
                verbose_name="Сезонність",
            ),
        ),
        migrations.AlterField(
            model_name="blanket",
            name="size",
            field=models.CharField(max_length=50, verbose_name="Розмір"),
        ),
        migrations.AlterField(
            model_name="pillow",
            name="brand",
            field=models.CharField(max_length=150, verbose_name="Бренд"),
        ),
        migrations.AlterField(
            model_name="pillow",
            name="cover_material",
            field=models.CharField(max_length=150, verbose_name="Матеріал чохла"),
        ),
        migrations.AlterField(
            model_name="pillow",
            name="filler",
            field=models.CharField(max_length=150, verbose_name="Наповнювач"),
        ),
        migrations.AlterField(
            model_name="pillow",
            name="size",
            field=models.CharField(max_length=50, verbose_name="Розмір"),
        ),
        migrations.AlterField(
            model_name="plaid",
            name="brand",
            field=models.CharField(max_length=150, verbose_name="Бренд"),
        ),
        migrations.AlterField(
            model_name="plaid",
            name="material",
            field=models.CharField(max_length=150, verbose_name="Матеріал"),
        ),
        migrations.AlterField(
            model_name="plaid",
            name="size",
            field=models.CharField(max_length=50, verbose_name="Розмір"),
        ),
        migrations.AlterField(
            model_name="plaid",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Дитячий"),
                    (1, "Полуторний"),
                    (2, "Двоспальний"),
                    (3, "Євро"),
                ],
                verbose_name="Спальний розмір",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="article",
            field=models.IntegerField(unique=True, verbose_name="Артикул"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Рушники"),
                    (1, "Ковдри"),
                    (2, "Постільна білизна"),
                    (3, "Подушки"),
                    (4, "Пледи"),
                    (5, "Покривала"),
                    (6, "Наматрацники"),
                    (7, "Скатертини"),
                    (8, "Декоративні наволочки"),
                    (9, "Кухонний текстиль"),
                    (10, "Простирадла"),
                ],
                verbose_name="Категорія",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=250, verbose_name="Назва"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(verbose_name="Ціна"),
        ),
        migrations.AlterField(
            model_name="product",
            name="producing_country",
            field=models.CharField(max_length=120, verbose_name="Країна виробництва"),
        ),
        migrations.AlterField(
            model_name="towel",
            name="brand",
            field=models.CharField(max_length=150, verbose_name="Бренд"),
        ),
        migrations.AlterField(
            model_name="towel",
            name="material",
            field=models.CharField(max_length=150, verbose_name="Матеріал"),
        ),
        migrations.AlterField(
            model_name="towel",
            name="size",
            field=models.CharField(max_length=50, verbose_name="Розмір"),
        ),
        migrations.AlterField(
            model_name="towel",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Для рук"),
                    (1, "Для обличчя"),
                    (2, "Банні"),
                    (3, "Сауна"),
                    (4, "Набори"),
                    (5, "Куточки"),
                ],
                verbose_name="Тип",
            ),
        ),
        migrations.CreateModel(
            name="Tablecloths",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(max_length=50, verbose_name="Розмір")),
                ("material", models.CharField(max_length=150, verbose_name="Матеріал")),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tablecloths",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Скатертина",
                "verbose_name_plural": "Скатертини",
            },
        ),
        migrations.CreateModel(
            name="Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=150, verbose_name="Бренд")),
                ("size", models.CharField(max_length=50, verbose_name="Розмір")),
                (
                    "material",
                    models.PositiveSmallIntegerField(choices=[(0, "Лляні"), (1, "Махрові")], verbose_name="Матеріал"),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sheets",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Простирадло",
                "verbose_name_plural": "Простирадла",
            },
        ),
        migrations.CreateModel(
            name="Pillowcase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(max_length=50, verbose_name="Розмір")),
                ("material", models.CharField(max_length=150, verbose_name="Матеріал")),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pillowcase",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Декоративна наволочка",
                "verbose_name_plural": "Декоративні наволочки",
            },
        ),
        migrations.CreateModel(
            name="MattressCovers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(max_length=50, verbose_name="Розмір")),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Дитячий"),
                            (1, "Односпальний"),
                            (2, "Полуторний"),
                            (3, "Двоспальний"),
                            (4, "Євро"),
                        ],
                        verbose_name="Спальний розмір",
                    ),
                ),
                (
                    "cover_material",
                    models.CharField(max_length=150, verbose_name="Матеріал чохла"),
                ),
                ("filler", models.CharField(max_length=150, verbose_name="Наповнювач")),
                (
                    "type_fastening",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "З бортами"), (1, "З резинкою по кутках")],
                        verbose_name="Тип кріплення",
                    ),
                ),
                (
                    "characteristic",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Водонепроникні"), (1, "Стьобаний")],
                        verbose_name="Особливості",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mattress_covers",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Наматрацник",
                "verbose_name_plural": "Наматрацники",
            },
        ),
        migrations.CreateModel(
            name="KitchenTextile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "age_group",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Дитячий"), (1, "Дорослий")],
                        verbose_name="Вікова група",
                    ),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Фартух"), (1, "Прихватка"), (2, "Рукавиця")],
                        verbose_name="Тип товару",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kitchen_textiles",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кухонний текстиль",
                "verbose_name_plural": "Кухонний текстиль",
            },
        ),
    ]
