# Generated by Django 4.2.7 on 2023-12-15 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_product_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.category",
                verbose_name="Категорія",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="producing_country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.producingcountry",
                verbose_name="Країна виробництва",
            ),
        ),
    ]
