# Generated by Django 4.2.7 on 2023-12-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_alter_product_category_and_more"),
        ("order", "0002_remove_order_email_remove_order_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="items",
            field=models.ManyToManyField(blank=True, null=True, through="order.CartItem", to="products.product"),
        ),
    ]
