# Generated by Django 4.2.7 on 2023-12-09 19:16

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_remove_cartitem_added_at_alter_cartitem_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=150, verbose_name="Ім'я")),
                (
                    "last_name",
                    models.CharField(max_length=150, verbose_name="Прізвище"),
                ),
                (
                    "middle_name",
                    models.CharField(max_length=150, verbose_name="По батькові"),
                ),
                ("email", models.EmailField(max_length=150, verbose_name="Пошта")),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Номер телефону",
                    ),
                ),
                (
                    "delivery_method",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Нова пошта"), (1, "Укрпошта")],
                        verbose_name="Категорія",
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Місто")),
                (
                    "branch_address",
                    models.CharField(max_length=255, verbose_name="Адреса відділення"),
                ),
                (
                    "order_status",
                    models.CharField(
                        default="В обробці",
                        max_length=50,
                        verbose_name="Статус замовлення",
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order.cart",
                        verbose_name="Кошик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Замовлення",
                "verbose_name_plural": "Замовлення",
            },
        ),
    ]
