# Generated by Django 4.2.5 on 2024-01-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_alter_order_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="cart",
            field=models.TextField(verbose_name="Кошик"),
        ),
    ]
