# Generated by Django 4.2.7 on 2023-12-09 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_bedlinen_options_alter_bedspread_options_and_more"),
        ("order", "0003_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="items",
        ),
        migrations.AddField(
            model_name="cart",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Кількість"),
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
