# Generated by Django 4.2.7 on 2023-12-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0005_remove_cart_product_remove_cart_quantity_cartitem_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="order_status",
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Оплата при доставці"), (1, "Переказ на карту")],
                default=0,
                verbose_name="Спосіб оплати",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_method",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Нова пошта"), (1, "Укрпошта")],
                verbose_name="Спосіб доставки",
            ),
        ),
    ]
