# Generated by Django 4.2.5 on 2024-01-12 15:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="avatar",
        ),
    ]
